// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package http

import (
	"github.com/conduitio/conduit-commons/config"
)

func (DestinationConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		"headers": {
			Default:     "",
			Description: "Http headers to use in the request, comma separated list of : separated pairs",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"method": {
			Default:     "POST",
			Description: "Http method to use in the request",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"POST", "PUT", "DELETE", "PATCH"}},
			},
		},
		"params": {
			Default:     "",
			Description: "parameters to use in the request, comma separated list of : separated pairs",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"url": {
			Default:     "",
			Description: "Http url to send requests to",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
